# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hcbox < Formula
  desc "hcbox is a toolbox for managing hetzner cloud development/testing servers."
  homepage "https://github.com/reckerp/hcbox"
  version "1.0.0"

  on_macos do
    url "https://github.com/reckerp/hcbox/releases/download/v1.0.0/hcbox_Darwin_all.tar.gz"
    sha256 "dba66fb99c3dc909b3adcaf40dd44c23a0a50ec9ae7b07367395d4a2a55ad0e1"

    def install
      bin.install "hcbox"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/reckerp/hcbox/releases/download/v1.0.0/hcbox_Linux_x86_64.tar.gz"
      sha256 "2b31354572ca31a4971af5c17a9fa606cd6cc913a930616fd1cd963f570342cf"
      def install
        bin.install "hcbox"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/reckerp/hcbox/releases/download/v1.0.0/hcbox_Linux_arm64.tar.gz"
      sha256 "de99a08d52edcb9abfeca67f1914fc1beec6de90cc7dcb7e028cf53efefe7039"
      def install
        bin.install "hcbox"
      end
    end
  end

  test do
    system "#{bin}/hcbox", "--help"
  end
end
